server:  
  port: ${PORT:3333}

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
    
Hystrix:
  hystrix:
    command:
      default:
        execution:
          isolation:
            strategy: SEMAPHORE
            thread:
              timeout-in-milliseconds: 10000
        circuit-breaker:
          enabled: true
          error-threshold-percentage: 10
          sleep-window-in-milliseconds: 20000
          request-volume-threshold: 2
    