server:  
  port: ${PORT:2222}



eureka: 
  client:
    healthcheck:
      enabled: true          
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    prefer-same-zone-eureka: true

  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    

   
#ribbon:
#    eureka:
#      enabled: true
#   
#Hystrix:
#  hystrix:
#    command:
#      default:
#        execution:
#          isolation:
#            strategy: SEMAPHORE
#            thread:
#              timeout-in-milliseconds: 10000
#        circuit-breaker:
#          enabled: true
#          error-threshold-percentage: 50
#          sleep-window-in-milliseconds: 50000
#          request-volume-threshold: 3
          

        
  

  
  
  

  